# 飞书应用配置
# 飞书应用ID
lark.app.id=cli_a81701bdb4f2100e
# 飞书应用密钥
lark.app.secret=dLg8ZfVXzTDuE1QY1p7vee5YrFAfSJad
# 飞书回调地址 - 使用aegis.tst.spotter.ink域名
lark.redirect.uri=http://aegis.tst.spotter.ink/devops/feishu/callback
